services:
  db:
    image: postgres:15
    container_name: pg_arbitraje_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: arbitrage_db
    ports:
      - "5433:5432" 
    volumes:
      - pg_data_final:/var/lib/postgresql/data

  monitor_app:
    build: .
    container_name: python_arbitraje_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
    restart: always

volumes:
  pg_data_final: